//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public car()
        {
            this.offer_slots = new HashSet<offer_slots>();
            this.request_slots = new HashSet<request_slots>();
        }
    
        public int id { get; set; }
        public string plate { get; set; }
        public string color { get; set; }
        public string brand { get; set; }
        public int cartype_id { get; set; }
        public int driver_id { get; set; }
    
        public virtual car_types car_types { get; set; }
        public virtual ICollection<offer_slots> offer_slots { get; set; }
        public virtual ICollection<request_slots> request_slots { get; set; }
        public virtual driver driver { get; set; }
    }
}
