//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public string tabname { get; set; }
        public string colname { get; set; }
        public System.DateTime timestamp { get; set; }
        public int rowid { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
