//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pairparkEntities : DbContext
    {
        public pairparkEntities()
            : base("name=pairparkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car_types> car_types { get; set; }
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<handshake_statuses> handshake_statuses { get; set; }
        public virtual DbSet<handshake> handshakes { get; set; }
        public virtual DbSet<history> histories { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<offer_slots> offer_slots { get; set; }
        public virtual DbSet<parameter> parameters { get; set; }
        public virtual DbSet<proposed_handshakes> proposed_handshakes { get; set; }
        public virtual DbSet<request_slots> request_slots { get; set; }
        public virtual DbSet<tracking> trackings { get; set; }
        public virtual DbSet<driver> drivers { get; set; }
    }
}
