//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracking
    {
        public int id { get; set; }
        public int driver_id { get; set; }
        public decimal longitude { get; set; }
        public decimal latitude { get; set; }
        public System.DateTime track_timestamp { get; set; }
    
        public virtual driver driver { get; set; }
    }
}
